version: '3.8' 
services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mynetwork
    volumes:
      - ./Frontend:/app

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./Backend:/app

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - mynetwork
    ports: 
      - "6379:6379"

networks:
  mynetwork:
    driver: bridge
